<div class="localnos col flex" onClick="jQuery('.numberslist').toggle();"><strong>01642 931 329</strong> Locations <i class="fa fa-chevron-down"></i>
    <div class="numberslist" style="display: none;">
        <ul>
            <li><a href="tel:01642 931 329"><span>North East: 01642 931 329</span></a>
            </li>
            <li><a href="tel:0161 674 0167"><span>Manchester: 0161 674 0167</span></a>
            </li>
            <li><a href="tel:0203 829 5779"><span>London: 0203 829 5779</span></a>
            </li>
        </ul>
    </div>
</div>
<div class="intno mr-auto col flex">
    <a href="tel:+44 203 829 5782"><span>International: <strong>+44 203 829 5782</strong></span></a>
</div>