<?php 


// function to create the menu
// FIX: Move this to a module
$menu = $block->getMenu();


function createMenu(\Magento\Framework\Data\Tree\Node $menu)
{
    $html ='';

    $children = $getChildren->getChildren();


    return $html;
}





$columnsLimit = $block->getColumnsLimit() ?: 0; ?>
<?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit) ?>

<nav class="navigation" data-action="navigation">
    <ul data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
        <?= /* @escapeNotVerified */ $_menu ?>
        <?= /* @escapeNotVerified */ $block->getChildHtml() ?>
    </ul>
</nav>
