<?php 
    // footer row 2
?>
<div class="footer-links-border">
    <div class="container">
        <div class="flex">
            <div class="flex-1">
                <h5>Secure Payments</h5>
                <p>We accept purchase orders or pay by</p>
                card images
            </div>
            <div class="flex-1">
                <h5>Connect With Us</h5>
                <p>Be the first to know the latest deals</p>
                social links
            </div>
            <div class="flex-1">
                <h5>Additional Services</h5>
                <p>Visit the PASS group site to learn aboutour calibration and training services</p>
                <a href="https://www.pass.co.uk">Visit PASS.co.uk <i class="fa fa-angle-right"></i></a>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="flex">
        <div class="flex-1 iso-accreditation">ISO IMAGE</div>
        <div class="flex-1 iso-accreditation">ISO IMAGE</div>
        <div class="flex-1 iso-accreditation">ISO IMAGE</div>
        <div class="flex-1 iso-accreditation">ISO IMAGE</div>
        <div class="flex-1 iso-accreditation">ISO IMAGE</div>
        <div class="flex-1 iso-accreditation">ISO IMAGE</div>
    </div>
</div>