<?php 
    // footer row 1
?>
<div class="footer-row-one-content">
    <div class="container">
        <div class="flex">
            <a href="#" class="flex-1">Contact-Us</a>
            <a href="#" class="flex-1">Customer Service</a>
            <a href="#" class="flex-1">Blog</a>
            <a href="#" class="flex-1">Catalogue Request</a>
            <a href="#" class="flex-1">Calibration</a>
            <a href="#" class="flex-1">Finance</a>
            <a href="#" class="flex-1">Returns</a>
            <a href="#" class="flex-1">Delivery</a>
        </div>
    </div>
</div>
