<?php
// Brands slider
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$catId = 110; // Parent Category ID
$subcategory = $objectManager->create('Magento\Catalog\Model\Category')->load($catId);
$subcats = $subcategory->getChildrenCategories();
$_helper = $this->helper('Magento\Catalog\Helper\Output');

if($subcats->getSize()>=4):
?>
<div class="col">
    <ul class="slider" id="brands">
    <?php
    foreach ($subcats as $subcat) {

        $_category = $objectManager->create('Magento\Catalog\Model\Category')->load($subcat->getId());
        $_outputhelper = $this->helper('Magento\Catalog\Helper\Output');
        $subcaturl = $subcat->getUrl();
        $_imgHtml = '';

        if ($_imgUrl = $_category->getImageUrl()) {
            $_imgHtml = '<img src="' . $_imgUrl . '" />';
            $_imgHtml = $_outputhelper->categoryAttribute($_category, $_imgHtml, 'image');
        }
        ?>
    <li>
        <div class="cat-image">
            <a href="<?php echo $subcaturl ?>"><?php echo $_imgHtml;?></a>
        </div>
    </li>
    <?php } ?>
    </ul>
</div>
<script>
require(['jquery', 'slick'],function($){
    $(document).ready(function(){
        $('.slider').slick({
            infinite: true,
            slidesToShow: 5,
            slidesToScroll: 5
        });
    });
});
</script>
<?php else: ?>
<div class="row">
        <div class="col-12" style="text-align:center;height:100px; background-color:#ebebeb; box-shadow:inset 0px 0px 15px #555555">
            Category for brands is missing please create it 
        </div>
</div>
<br>

<?php endif; ?>