<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Newsletter\Block\Subscribe $block */

?>
<div class="flex newsletter">
    <div class="title flex-1 p-1">
        <strong>
            Subscribe to our <br> Newsletter
        </strong>
    </div>
    <div class="newsletter flex-1 p-1">
        Subscribe to our newsletter and know first about all our promotions and discounts.
    </div>
    <div class="form flex-1 p-1">
        <form class="form subscribe"
            novalidate
            action="<?= $block->escapeUrl($block->getFormActionUrl()) ?>"
            method="post"
            data-mage-init='{"validation": {"errorClass": "mage-error"}}'
            id="newsletter-validate-detail">


                    <input name="email" type="email" id="newsletter"
                                placeholder="<?= $block->escapeHtmlAttr(__('Enter your email address')) ?>"
                                data-validate="{required:true, 'validate-email':true}"/>

                <button class="action subscribe primary" title="<?= $block->escapeHtmlAttr(__('Subscribe')) ?>" type="submit">
                    <span><?= $block->escapeHtml(__('Subscribe')) ?></span>
                </button>

        </form>
    </div>
</div>
